### ISSUE TITLE
Elasticsearch and Kibana 6.4.0 released

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#14]
@pjhampton Please, release a compatible version!

**Comment by pjhampton** [comment]
Thanks, @nikolay.

Please see: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.0

**Comment by nikolay** [comment]
@pjhampton I don't think this upgrade is trivial though. I keep getting this error:

```
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined
    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:7:68)
    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)
    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)
    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by pjhampton** [comment]
Hmm, interesting. I will look into this weekend @nikolay 
Thanks for bringing this to my attention

**Comment by nikolay** [comment]
@pjhampton Here's a snapshot of the metrics in 6.4.0 (with the `?extended` flag):

```JSON
{
  "kibana": {
    "uuid": "fbd87c65-a562-4bc3-a0cb-1454d9a4c8b2",
    "name": "kibana",
    "index": ".kibana",
    "host": "0",
    "transport_address": "0:5601",
    "version": "6.4.0",
    "snapshot": false,
    "status": "green"
  },
  "last_updated": "2018-08-31T10:05:10.431Z",
  "collection_interval_ms": 5000,
  "process": {
    "memory": {
      "heap": {
        "total_bytes": 101244928,
        "used_bytes": 88682680,
        "size_limit": 1501560832
      },
      "resident_set_size_bytes": 165072896
    },
    "event_loop_delay": 0.28190112113952637,
    "pid": 1,
    "uptime_ms": 1648222
  },
  "os": {
    "load": {
      "1m": 0.13427734375,
      "5m": 0.21826171875,
      "15m": 0.35205078125
    },
    "memory": {
      "total_bytes": 29479366656,
      "free_bytes": 11163906048,
      "used_bytes": 18315460608
    },
    "uptime_ms": 1202042000,
    "cgroup": {
      "cpuacct": {
        "control_group": "/",
        "usage_nanos": 13928993759
      },
      "cpu": {
        "control_group": "/",
        "cfs_period_micros": 100000,
        "cfs_quota_micros": 100000,
        "stat": {
          "number_of_elapsed_periods": 2660,
          "number_of_times_throttled": 184,
          "time_throttled_nanos": 14066301719
        }
      }
    }
  },
  "response_times": {
    "avg_ms": 4,
    "max_ms": 4
  },
  "requests": {
    "total": 1,
    "disconnects": 0,
    "status_codes": {
      "200": 1
    }
  },
  "concurrent_connections": 0,
  "usage": {
    
  },
  "cluster_uuid": "tCB6fU_OQUeempU_JhdMSA"
}
```

**Comment by pjhampton** [comment]
Also if you could let me know where you are getting that release info from that would be great. Are you subscribed to a feed of some sort?

**Comment by nikolay** [comment]
Huge thanks, @pjhampton!

**Comment by nikhil-bhat** [comment]
hi @pjhampton i was able to avoid the ssl issue #3  in the 6.6.2 version of plugin.
could you release a version of 6.4.0 with support for ssl .
I tried comparing code between 6.4.0 release and 6.6.2 the folder structure has changed . 
but i could find the reason why the ssl error is not ocuuring . is it because of different library being used  request-promise 6.6.2 and request in 6.4.0

**Comment by pjhampton** [comment]
Hey @nikhil-bhat 👋 ,

Sure thing. Please open a new issue though than surface old ones. That's how things never get done :)
