### ISSUE TITLE
 Unable to read kibana.json file for plugin kibanaPrometheusExporter

### ISSUE THREAD

**Issue by AlbusLumos** [pjhampton/kibana-prometheus-exporter#298]
Seems the installation is failure, i visited the http://localhost:5601/_prometheus/metrics and got 404 not found

And i use the below command to show installed plugin, i got :

/usr/share/kibana/src/cli_plugin/list/list.js:23
  plugins.forEach(([name]) => {
          ^
Error: Unable to read kibana.json file for plugin kibanaPrometheusExporter
    at /usr/share/kibana/src/cli_plugin/list/list.js:29:13
    at Array.forEach (<anonymous>)
    at list (/usr/share/kibana/src/cli_plugin/list/list.js:23:11)
    at Command.processCommand (/usr/share/kibana/src/cli_plugin/list/index.js:22:18)
    at Command.<anonymous> (/usr/share/kibana/src/cli/command.js:84:20)
    at Command.listener (/usr/share/kibana/node_modules/commander/index.js:370:29)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/usr/share/kibana/node_modules/commander/index.js:892:12)
    at Command.parse (/usr/share/kibana/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/usr/share/kibana/src/cli_plugin/cli.js:41:9)

does anyone have any idea how to fix?

**Comment by pjhampton** [comment]
@AlbusLumos 

Apologies - I'm only getting caught up on open source work.

  1. Can you please tell me what version of Kibana you are running?
  2. How are you installing it?

**Comment by pjhampton** [comment]
Hey @AlbusLumos 

I'm going to close this. Feel free to reopen if you are still causing issues.
