### ISSUE TITLE
6.1.1 is internal error 500

### ISSUE THREAD

**Issue by sergeohl** [pjhampton/kibana-prometheus-exporter#3]
When I use the version 6.1.1 I have an internal error 500 when I try to reach `_prometheus/metrics `

**Comment by sergeohl** [comment]
Yes the version is ok. 

But I think the issue is in the https validation

**Comment by pjhampton** [comment]
Hey @sergeohl did you ever get to the bottom of this?

**Comment by sergeohl** [comment]
Not yet I'm stuck with 

`{"type":"error","@timestamp":"2018-05-23T17:35:28Z","tags":[],"pid":1,"level":"error","error":{"message":"Hostname/IP doesn't match certificate's altnames: \"IP: 0.0.0.0 is not in the cert's list: \"","name":"Error","stack":"Error: Hostname/IP doesn't match certificate's altnames: \"IP: 0.0.0.0 is not in the cert's list: \"\n    at Object.checkServerIdentity (tls.js:199:17)\n    at TLSSocket.<anonymous> (_tls_wrap.js:1098:29)\n    at emitNone (events.js:86:13)\n    at TLSSocket.emit (events.js:185:7)\n    at TLSSocket._finishInit (_tls_wrap.js:610:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"Hostname/IP doesn't match certificate's altnames: \"IP: 0.0.0.0 is not in the cert's list: \""}`

I have x-pack I think it is a kibana setting but I cannot find it

**Comment by sergeohl** [comment]
So the issue is not in my side but in the plugins. 

Node,js and request do a hostname verification and in my case (kubernetes, loadbalancing) is not working. 
In kibana I disable le ssl name verification, but the plugin doesn't care about it.

**Comment by pjhampton** [comment]
Hmm, interesting. Is it all plugins or just this one?
Do you have steps that I can reproduce?

**Comment by pjhampton** [comment]
I'm going to close this out @sergeohl. If you want to chat about this further we can always reopen.

Thanks for supporting this project!

**Comment by JPLachance** [comment]
Hello!

Since you released a version of your plugin for Kibana 6.3.2 that supports the X-Pack authentication (#31), I now hit the exact same issue my colleague @sergeohl reported.

In my kibana.yml file, I enabled SSL:
```YAML
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certificate/kibana-cert.pem
server.ssl.key: /usr/share/kibana/config/certificate/kibana-cert.key
```

Then, when I try to access the `https://my.domain.com/_prometheus/metrics` endpoint, I either see:
```
RequestError: Error: self signed certificate
    at new RequestError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
```
when I use a self signed certificate, or:
```
RequestError: Error: Hostname/IP doesn't match certificate's altnames: "IP: 0.0.0.0 is not in the cert's list: "
    at new RequestError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
```
when I use a legitimate certificate.

I have multiple plugins in Kibana, and only the Prometheus exporter is complaning.

Any clue how we can work around this issue? :)

Thanks!

**Comment by pjhampton** [comment]
Reopening for investigation.

**Comment by pjhampton** [comment]
I suppose I could implement this and create a release candidate. I won't be able to reproduce this easily in my set up so would you mind working with me on this one to install the release candidate and tell me if it works?

https://github.com/request/request#tlsssl-protocol

**Comment by JPLachance** [comment]
Hello!

Yes, I can test it for you. Just ship me the link then I'll build a new container image with your plugin in it. I use Kibana 6.3.2.

In my kibana.yml file, I have:
```
# This setting specifies the IP address of the back end server.
server.host: "0.0.0.0"
```

I think that is why I see the error `Hostname/IP doesn't match certificate's altnames: "IP: 0.0.0.0 is not in the cert's list: "`. 

Since my Kibana container runs in Kubernetes, I don't think I can set another value for `server.host`.

I found a workaround to make the Prometheus exporter work:
``` 
env:
  - name: NODE_TLS_REJECT_UNAUTHORIZED
    value: '0'
```

By setting the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0`, it starts working 🎉  But that's an ugly workaround since it disables TLS for Kibana too.

In [prometheus.js](https://github.com/pjhampton/kibana-prometheus-exporter/blob/master/server/exporter/prometheus.js#L14), I think we can add `rejectUnauthorized: false` and request will trowing when calling `/api/status?extended`.

Poke me when you'll have that release candidate! 😄

**Comment by pjhampton** [comment]
@JPLachance 

See: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.2-ssl-rc

Let me know if it works / doesn't! :) Thanks for your support

**Comment by JPLachance** [comment]
Hello,

I installed it and I got the following error on boot:
```
FATAL ReferenceError: cert is not defined
    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/exporter/prometheus.js:25:13)
    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/kibana-prometheus-exporter/index.js:28:7)
    at asyncRegister (/usr/share/kibana/src/server/plugins/lib/plugin.js:72:20)
    at Object.register (/usr/share/kibana/src/server/plugins/lib/plugin.js:77:7)
    at Object.target [as register] (/usr/share/kibana/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/usr/share/kibana/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/usr/share/kibana/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/usr/share/kibana/node_modules/items/lib/index.js:39:9)
    at module.exports.internals.Server.internals.Plugin.register (/usr/share/kibana/node_modules/hapi/lib/plugin.js:320:11)
    at Promise (/usr/share/kibana/node_modules/hapi/lib/promises.js:24:16)
    at new Promise (<anonymous>)
    at Object.exports.wrap (/usr/share/kibana/node_modules/hapi/lib/promises.js:13:12)
    at module.exports.internals.Server.internals.Plugin.register (/usr/share/kibana/node_modules/hapi/lib/plugin.js:164:25)
    at Plugin.init (/usr/share/kibana/src/server/plugins/lib/plugin.js:82:28)
    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7363:25)
    at callPluginHook (/usr/share/kibana/src/server/plugins/lib/call_plugin_hook.js:37:25)
    at callHookOnPlugins (/usr/share/kibana/src/server/plugins/initialize_mixin.js:28:37)
    at <anonymous>
```

Is there anything I need to configure?

Thanks!

**Comment by pjhampton** [comment]
@JPLachance please try again. I updated the rc binary.

**Comment by JPLachance** [comment]
Hello!

I'm back to:
```
RequestError: Error: Hostname/IP doesn't match certificate's altnames: "IP: 0.0.0.0 is not in the cert's list: "
    at new RequestError (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/share/kibana/plugins/kibana-prometheus-exporter/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitOne (events.js:116:13)
```

My guess is that the JS code takes the value of `server.host` in the `kibana.yml` file and request is using that value (0.0.0.0) for the certificate validation.

Do we really need a certificate validation between the Kibana Prometheus exporter and the Kibana server? :) I think we could simply drop that validation, it's not a critical security issue for that specific task.

**Comment by pjhampton** [comment]
@JPLachance please try again. I updated the rc binary.

Yeah - I've now applied your suggestion. Might need to add a bit more config in though to bypass

**Comment by pjhampton** [comment]
@JPLachance I have managed to replicate this now and that rc should now work. Please confirm.

**Comment by JPLachance** [comment]
Hello!

I'm sorry, I was traveling 🙂 

This final version works as expected 🎉 

Thanks a lot for this fix.

Will you release an official version with this fix?

Regards,
JP

**Comment by pjhampton** [comment]
That's cool @JPLachance - hope you had a good time.
Great to read. Yeah - I will release tonight :)

**Comment by pjhampton** [comment]
Hey it's updated here: https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.3.2
