### ISSUE TITLE
Merge updated metric names back in time

### ISSUE THREAD

**Issue by pjhampton** [pjhampton/kibana-prometheus-exporter#35]
Need to merge PR https://github.com/pjhampton/kibana-prometheus-exporter/pull/20 back into the other branches and release

**Comment by siwyd** [comment]
Would appreciate this for the 6.3.2 release as AWS is still stuck on 6.3 for now for their hosted service.

**Comment by pjhampton** [comment]
Hey @siwyd 

This was introduced in 6.3.2 so it should work out of the box. Are you having issues?

**Comment by pjhampton** [comment]
Yeah, you are right - apologies! 
I will look into this tonight

**Comment by siwyd** [comment]
Cool, cheers!!

**Comment by pjhampton** [comment]
Please try again @siwyd 👍

**Comment by siwyd** [comment]
@pjhampton I seem to getting a build error with above Dockerfile:
```❯ docker build . --no-cache
Sending build context to Docker daemon  54.78kB
Step 1/2 : FROM docker.elastic.co/kibana/kibana-oss:6.3.2
 ---> 9d655c318834
Step 2/2 : RUN kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.3.2/kibana-prometheus-exporter-6.3.2.zip
 ---> Running in 92ec9e532994
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.3.2/kibana-prometheus-exporter-6.3.2.zip
Transferring 42074 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:16) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
FATAL { ValidationError: child "kibana-prometheus-exporter" fails because [child "user" fails because ["user" is not allowed to be empty], child "pass" fails because ["pass" is not allowed to be empty]]
    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)
    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)
    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)
    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)
    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)
    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:26:10)
    at <anonymous>
  isJoi: true,
  name: 'ValidationError',
  details: 
   [ { message: '"user" is not allowed to be empty',
       path: 'kibana-prometheus-exporter.user',
       type: 'any.empty',
       context: [Object] },
     { message: '"pass" is not allowed to be empty',
       path: 'kibana-prometheus-exporter.pass',
       type: 'any.empty',
       context: [Object] } ],
  _object: 
   { pkg: 
      { version: '6.3.2',
        branch: '6.3',
        buildNum: 17307,
        buildSha: '53d0c6758ac3fb38a3a1df198c1d4c87765e63f7' },
     dev: { basePathProxyTarget: 5603 },
     pid: { exclusive: false },
     cpu: undefined,
     cpuacct: undefined,
     server: 
      { name: 'kibana',
        host: '0',
        autoListen: false,
        port: 5601,
        maxPayloadBytes: 1048576,
        defaultRoute: '/app/kibana',
        basePath: '',
        rewriteBasePath: false,
        customResponseHeaders: {},
        ssl: [Object],
        cors: false,
        xsrf: [Object] },
     logging: 
      { silent: false,
        quiet: false,
        verbose: false,
        events: {},
        dest: 'stdout',
        filter: {},
        json: true,
        useUTC: true },
     ops: { interval: 5000 },
     plugins: { scanDirs: [Array], paths: [], initialize: false },
     path: { data: '/usr/share/kibana/data' },
     optimize: 
      { useBundleCache: false,
        enabled: true,
        bundleFilter: '!tests',
        bundleDir: '/usr/share/kibana/optimize/bundles',
        viewCaching: true,
        watch: false,
        watchPort: 5602,
        watchHost: 'localhost',
        watchPrebuild: false,
        watchProxyTimeout: 300000,
        profile: false },
     status: { allowAnonymous: false },
     map: 
      { manifestServiceUrl: 'https://catalogue.maps.elastic.co/v2/manifest',
        includeElasticMapsService: true },
     tilemap: { options: [Object] },
     regionmap: { includeElasticMapsService: true },
     i18n: { defaultLocale: 'en' },
     input_control_vis: { enabled: true },
     kbn_doc_views: { enabled: true },
     kbn_vislib_vis_types: { enabled: true },
     markdown_vis: { enabled: true },
     metric_vis: { enabled: true },
     region_map: { enabled: true },
     state_session_storage_redirect: { enabled: true },
     spy_modes: { enabled: true },
     status_page: { enabled: true },
     table_vis: { enabled: true },
     tagcloud: { enabled: true },
     tile_map: { enabled: true },
     timelion: { enabled: true },
     'kibana-prometheus-exporter': 
      { enabled: true,
        path: '/_prometheus/metrics',
        user: '',
        pass: '' },
     console: undefined },
  annotate: [Function] }

{"type":"log","@timestamp":"2018-11-27T20:11:16Z","tags":["warning","config","deprecation"],"pid":16,"message":"uiSettings.enabled is deprecated and is no longer used"}
{"type":"error","@timestamp":"2018-11-27T20:11:17Z","tags":["fatal"],"pid":16,"level":"fatal","error":{"message":"child \"kibana-prometheus-exporter\" fails because [child \"user\" fails because [\"user\" is not allowed to be empty], child \"pass\" fails because [\"pass\" is not allowed to be empty]]","name":"ValidationError","stack":"ValidationError: child \"kibana-prometheus-exporter\" fails because [child \"user\" fails because [\"user\" is not allowed to be empty], child \"pass\" fails because [\"pass\" is not allowed to be empty]]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)\n    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)\n    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)\n    at Config._commit (/usr/share/kibana/src/server/config/config.js:119:35)\n    at Config.set (/usr/share/kibana/src/server/config/config.js:89:10)\n    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:62:10)\n    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:26:10)\n    at <anonymous>"},"message":"child \"kibana-prometheus-exporter\" fails because [child \"user\" fails because [\"user\" is not allowed to be empty], child \"pass\" fails because [\"pass\" is not allowed to be empty]]"}
"
The command '/bin/sh -c kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.3.2/kibana-prometheus-exporter-6.3.2.zip' returned a non-zero code: 70
```

**Comment by pjhampton** [comment]
Woah - that branch was borked. Ok - for reals this time. Please try again.

**Comment by siwyd** [comment]
Works! Thanks very much!

**Comment by davsouza** [comment]
I am having the same issue with 6.2.2, we have also been stuck at this version for sometime, could you merge the change?
```
# HELP kibana_os_cpu_load_average{interval="1m"} kibana_os_cpu_load_average{interval="1m"}
# TYPE kibana_os_cpu_load_average{interval="1m"} gauge
kibana_os_cpu_load_average{interval="1m"} 0.01220703125
# HELP kibana_os_cpu_load_average{interval="5m"} kibana_os_cpu_load_average{interval="5m"}
# TYPE kibana_os_cpu_load_average{interval="5m"} gauge
kibana_os_cpu_load_average{interval="5m"} 0.0908203125
# HELP kibana_os_cpu_load_average{interval="15m"} kibana_os_cpu_load_average{interval="15m"}
# TYPE kibana_os_cpu_load_average{interval="15m"} gauge
kibana_os_cpu_load_average{interval="15m"} 0.19091796875
```
