### ISSUE TITLE
Exporter is crashing due to read property 'heap_max_in_bytes' of undefined

### ISSUE THREAD

**Issue by rameshpitchaiah** [pjhampton/kibana-prometheus-exporter#49]
Kibana is running as k8s pod with  prometheus exporter installed on it. But it is crashing with the read property undefined 
Kibana Version: 6.4.0

Setting in Kibana.yaml
server.basePath: /kibana
server.host: 0.0.0.0
server.name: kibana
~

Log Snippet:

```
{"type":"error","@timestamp":"2018-12-16T01:31:51Z","tags":[],"pid":1,"level":"error","error":{"message":"Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined","name":"TypeError","stack":"TypeError: Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined\n    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:7:68)\n    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)\n    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)\n    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1085:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/_prometheus/metrics","path":"/_prometheus/metrics","href":"/_prometheus/metrics"},"message":"Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined"}
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'heap_max_in_bytes' of undefined
    at exports.default (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/formatter.js:7:68)
    at getMetricsCallback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:22:15)
    at Request._callback (/usr/share/kibana/plugins/kibana-prometheus-exporter/server/routes/prometheus.js:38:5)
    at Request.self.callback (/usr/share/kibana/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/share/kibana/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
{"type":"response","@timestamp":"2018-12-16T01:31:51Z","tags":[],"pid":1,"method":"get","statusCode":500,"req":{"url":"/_prometheus/metrics","method":"get","headers":{"host":"app-firefly.com","connection":"close","x-real-ip":"104.36.248.13","x-forwarded-for":"104.36.248.13","x-forwarded-host":"app-firefly.com","x-forwarded-port":"443","x-forwarded-proto":"https","x-original-uri":"/kibana/_prometheus/metrics","x-scheme":"https","accept":"application/json, text/plain, */*","kbn-version":"6.4.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","referer":"https://app-fireflycom/kibana/app/kibana-prometheus-exporter","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"10.2.123.14","userAgent":"10.2.123.14","referer":"https://app-firefly.com/kibana/app/kibana-prometheus-exporter"},"res":{"statusCode":500,"responseTime":42,"contentLength":9},"message":"GET /_prometheus/metrics 500 42ms - 9.0B"}
{"type":"response","@timestamp":"2018-12-16T01:31:51Z","tags":[],"pid":1,"method":"get","statusCode":304,"req":{"url":"/ui/favicons/favicon-16x16.png","method":"get","headers":{"host":"app-firefly.com","connection":"close","x-real-ip":"104.36.248.13","x-forwarded-for":"104.36.248.13","x-forwarded-host":"app-firefly.com","x-forwarded-port":"443","x-forwarded-proto":"https","x-original-uri":"/kibana/ui/favicons/favicon-16x16.png","x-scheme":"https","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36","accept":"image/webp,image/apng,image/*,*/*;q=0.8","referer":"https://app-firefly.com/kibana/app/kibana-prometheus-exporter","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9","if-none-match":"\"13b869be5df4bdc56920edc16a28e67a7c08203b\"","if-modified-since":"Fri, 17 Aug 2018 23:26:52 GMT"},"remoteAddress":"10.2.123.14","userAgent":"10.2.123.14","referer":"https://app-firefly.com/kibana/app/kibana-prometheus-exporter"},"res":{"statusCode":304,"responseTime":1,"contentLength":9},"message":"GET /ui/favicons/favicon-16x16.png 304 1ms - 9.0B"}
```

Getting 500 Error when i execute curl

```
bash-4.2$ curl http://localhost:5601/_prometheus/metrics
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}bash-4.2$
```

**Comment by pathikritmodak** [comment]
Any update on this?

**Comment by pjhampton** [comment]
Yeah, I think I know the issue. This branch needs to be merged back in time: https://github.com/pjhampton/kibana-prometheus-exporter/blob/release/6.5.4/server/exporter/prometheus.js

Can you confirm the below curl XGET is ok with your basepath set up?

```
$ curl http://localhost:5601/kibana/_prometheus/metrics
```

**Comment by pathikritmodak** [comment]
Shows the same 500 error for me, I don't have the basepath set, also kibana isn't shared with ES, it's a separate instance behind proxy.

**Comment by pathikritmodak** [comment]
Let me know what details you would need to help debugging this further.

**Comment by pjhampton** [comment]
I think this might be 2 separate issues. Are you 2 working together so I can rule it out?

Do you have a stack trace like the one above or nothing at all?

**Comment by pathikritmodak** [comment]
No we aren't working together. I was getting the exact same stacktrace hence posted here.

I updated to the latest Kibana and the problem went away.

**Comment by pjhampton** [comment]
Hey. 

I updated the release. https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.0
Let me know if you have any more issues.

**Comment by gogi2811** [comment]
I am getting the same error as 

> Hey.
> 
> I updated the release. https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.0
> Let me know if you have any more issues.

I am getting the exact same error @pjhampton .
is there a different release for 6.4.0 version?

**Comment by pjhampton** [comment]
@gogi2811 I'm not sure -  please open a new issue and I will look into it for you :smiley_cat:
