### ISSUE TITLE
Issues with v6.8.0

### ISSUE THREAD

**Issue by nikolay** [pjhampton/kibana-prometheus-exporter#78]
```
Step 6/6 : RUN kibana-plugin install "https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/${KIBANA_PROMETHEUS_EXPORTER_VERSION}/kibana-prometheus-exporter-${KIBANA_PROMETHEUS_EXPORTER_VERSION}.zip"
 ---> Running in 0a452ac141d2
Attempting to transfer from https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.8.0/kibana-prometheus-exporter-6.8.0.zip
Transferring 1117793 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false

 FATAL  Error: Optimizations failure.
   1969 modules

    ERROR in ./plugins/kibana-prometheus-exporter/public/less/main.less
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleNotFoundError: Module not found: Error: Can't resolve '../prometheus_black.png' in '/usr/share/kibana/plugins/kibana-prometheus-exporter/public/less'
        at factory.create (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:814:10)
        at factory (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
        at resolver (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
        at asyncLib.parallel (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
        at /usr/share/kibana/node_modules/neo-async/async.js:2817:7
        at /usr/share/kibana/node_modules/neo-async/async.js:6783:13
        at normalResolver.resolve (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
        at doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn43 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
        at fs.stat (/usr/share/kibana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
        at process.nextTick (/usr/share/kibana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
        at process._tickCallback (internal/process/next_tick.js:61:11)



{"type":"log","@timestamp":"2019-05-28T17:45:05Z","tags":["info","plugins-service"],"pid":18,"message":"Plugin initialization disabled."}
{"type":"log","@timestamp":"2019-05-28T17:45:11Z","tags":["info","optimize"],"pid":18,"message":"Optimizing and caching bundles for kibana-prometheus-exporter, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
{"type":"log","@timestamp":"2019-05-28T17:45:59Z","tags":["fatal","root"],"pid":18,"message":"{ Error: Optimizations failure.\n   1969 modules\n    \n    ERROR in ./plugins/kibana-prometheus-exporter/public/less/main.less\n    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\n    ModuleNotFoundError: Module not found: Error: Can't resolve '../prometheus_black.png' in '/usr/share/kibana/plugins/kibana-prometheus-exporter/public/less'\n        at factory.create (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:814:10)\n        at factory (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:397:22)\n        at resolver (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:130:21)\n        at asyncLib.parallel (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:224:22)\n        at /usr/share/kibana/node_modules/neo-async/async.js:2817:7\n        at /usr/share/kibana/node_modules/neo-async/async.js:6783:13\n        at normalResolver.resolve (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:214:25)\n        at doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:184:12)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\n        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn43 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\n        at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)\n        at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n        at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n        at fs.stat (/usr/share/kibana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)\n        at process.nextTick (/usr/share/kibana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)\n        at process._tickCallback (internal/process/next_tick.js:61:11)\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:461:27)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:45:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:210:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:226:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:224:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:552:14)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:549:30)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1312:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeChunkAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1303:32)\n    at _err0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)\n    at taskRunner.run (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/index.js:315:9)\n    at step (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:76:9)\n    at done (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:84:30)\n    at boundWorkers (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:13)\n    at /usr/share/kibana/node_modules/worker-farm/lib/farm.js:191:19\n    at process._tickCallback (internal/process/next_tick.js:61:11)\n  cause:\n   { Error: Optimizations failure.\n      1969 modules\n       \n       ERROR in ./plugins/kibana-prometheus-exporter/public/less/main.less\n       Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\n       ModuleNotFoundError: Module not found: Error: Can't resolve '../prometheus_black.png' in '/usr/share/kibana/plugins/kibana-prometheus-exporter/public/less'\n           at factory.create (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:814:10)\n           at factory (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:397:22)\n           at resolver (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:130:21)\n           at asyncLib.parallel (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:224:22)\n           at /usr/share/kibana/node_modules/neo-async/async.js:2817:7\n           at /usr/share/kibana/node_modules/neo-async/async.js:6783:13\n           at normalResolver.resolve (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:214:25)\n           at doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:184:12)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n           at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\n           at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn43 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\n           at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)\n           at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\n           at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n           at fs.stat (/usr/share/kibana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)\n           at process.nextTick (/usr/share/kibana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)\n           at process._tickCallback (internal/process/next_tick.js:61:11)\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:461:27)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:45:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:210:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:226:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:224:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:552:14)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:549:30)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1312:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeChunkAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1303:32)\n       at _err0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)\n       at taskRunner.run (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/index.js:315:9)\n       at step (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:76:9)\n       at done (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:84:30)\n       at boundWorkers (/usr/share/kibana/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:13)\n       at /usr/share/kibana/node_modules/worker-farm/lib/farm.js:191:19\n       at process._tickCallback (internal/process/next_tick.js:61:11)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.23.1',\n        hash: '55414e129b22503e4ec0',\n        time: 46855,\n        builtAt: 1559065559147,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ './plugins/kibana-prometheus-exporter/public/less/main.less\\nModule build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):\\nModuleNotFoundError: Module not found: Error: Can\\'t resolve \\'../prometheus_black.png\\' in \\'/usr/share/kibana/plugins/kibana-prometheus-exporter/public/less\\'\\n    at factory.create (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:814:10)\\n    at factory (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:397:22)\\n    at resolver (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:130:21)\\n    at asyncLib.parallel (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:224:22)\\n    at /usr/share/kibana/node_modules/neo-async/async.js:2817:7\\n    at /usr/share/kibana/node_modules/neo-async/async.js:6783:13\\n    at normalResolver.resolve (/usr/share/kibana/node_modules/webpack/lib/NormalModuleFactory.js:214:25)\\n    at doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:184:12)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\\n    at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\\n    at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn43 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)\\n    at resolver.doResolve (/usr/share/kibana/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn1 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)\\n    at hook.callAsync (/usr/share/kibana/node_modules/enhanced-resolve/lib/Resolver.js:238:5)\\n    at _fn0 (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)\\n    at fs.stat (/usr/share/kibana/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)\\n    at process.nextTick (/usr/share/kibana/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)\\n    at process._tickCallback (internal/process/next_tick.js:61:11)\\n @ ./plugins/kibana-prometheus-exporter/public/app.js 11:0-27\\n @ ./optimize/bundles/kibana-prometheus-exporter.entry.js' ],\n     warnings: [],\n     version: '4.23.1',\n     hash: '55414e129b22503e4ec0',\n     time: 46855,\n     builtAt: 1559065559147,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n      { commons: [Array],\n        kibana: [Array],\n        'kibana-prometheus-exporter': 'kibana-prometheus-exporter.bundle.js',\n        stateSessionStorageRedirect: 'stateSessionStorageRedirect.bundle.js',\n        status_page: 'status_page.bundle.js',\n        timelion: 'timelion.bundle.js' },\n     assets:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints:\n      { 'kibana-prometheus-exporter': [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object] },\n     namedChunkGroups:\n      { 'kibana-prometheus-exporter': [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object] },\n     chunks:\n      [ [Object], [Object], [Object], [Object], [Object], [Object] ],\n     modules:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 1869 more items ],\n     filteredModules: 0,\n     children:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ] },\n  isBoom: true,\n  isServer: true,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
"
The command '/bin/sh -c kibana-plugin install "https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/${KIBANA_PROMETHEUS_EXPORTER_VERSION}/kibana-prometheus-exporter-${KIBANA_PROMETHEUS_EXPORTER_VERSION}.zip"' returned a non-zero code: 70
make: *** [docker-build] Error 70
```

**Comment by nikolay** [comment]
@pjhampton Sorry, I just tried to build my custom Docker image and it kept failing.

**Comment by pjhampton** [comment]
Hey @nikolay 

Looks like I made the same mistake in 6.8.0 as I did in 7.1.0. I have updated the branch and artifact. Can you please try again?

https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.8.0

**Comment by nikolay** [comment]
All working now! Thank you, @pjhampton! 🎉
